import type { SeedPath } from "./types";

export const paths: SeedPath[] = [
  {
    slug: "first-steps-into-marxism",
    title: "First steps into Marxism",
    entryLine: "I've never read Marx.",
    level: "introductory",
    estimatedTime: "About 2 hours across sessions",
    featured: true,
    sortOrder: 10,
    summary:
      "Ten ideas, in an order that builds: from what capitalism is, through value and exploitation, to how Marx understood history.",
    steps: [
      { ref: "concept:capitalism", framing: "Start with the object of the whole critique: what makes capitalism a distinct way of organising society." },
      { ref: "concept:class", framing: "Capitalism divides people by their relation to the means of production." },
      { ref: "concept:commodity", framing: "Capital begins with the commodity. Here is why." },
      { ref: "concept:labour", framing: "Two sides of labour: the concrete work you do, and the abstract time the market counts." },
      { ref: "concept:value", framing: "What makes things exchangeable in definite proportions?" },
      { ref: "concept:surplus-value", framing: "The central idea: where profit comes from." },
      { ref: "concept:exploitation", framing: "Why Marx calls the wage relation exploitative even when wages are fair." },
      { ref: "concept:alienation", framing: "What capitalism does to people's relation to their work, each other and themselves." },
      { ref: "concept:historical-materialism", framing: "Stepping back: Marx's way of reading history as a whole." },
      { ref: "concept:class-struggle", framing: "And the conflict that, for Marx, drives that history." },
    ],
  },
  {
    slug: "foundations",
    title: "The foundations",
    entryLine: "Give me the foundations.",
    level: "introductory",
    estimatedTime: "About 3 hours",
    featured: true,
    sortOrder: 20,
    summary:
      "From the French Revolution and Hegel to the First International: where socialist theory came from, and the first great split.",
    steps: [
      { ref: "event:french-revolution", framing: "The political vocabulary of the left begins here." },
      { ref: "thinker:hegel", framing: "The philosophy the young radicals inherited — and fought over." },
      { ref: "thinker:proudhon", framing: "The first self-described anarchist, and Marx's early interlocutor." },
      { ref: "text:communist-manifesto", framing: "The most widely read socialist text, written for a small league on the eve of 1848." },
      { ref: "concept:historical-materialism", framing: "The method behind the Manifesto." },
      { ref: "event:first-international", framing: "Socialists and trade unionists organise internationally." },
      { ref: "thinker:bakunin", framing: "The great dissenter inside the International." },
      { ref: "event:paris-commune", framing: "The event everyone claimed." },
    ],
  },
  {
    slug: "marxist-debates",
    title: "Into the Marxist debates",
    entryLine: "Take me into Marxist debates.",
    level: "intermediate",
    estimatedTime: "About 3 hours",
    featured: true,
    sortOrder: 30,
    summary:
      "The arguments that divided Marxists from the 1890s onwards — on reform, the party, the state and consciousness.",
    steps: [
      { ref: "debate:reform-or-revolution", framing: "The revisionism controversy: the first great internal split." },
      { ref: "thinker:luxemburg", framing: "Bernstein's sharpest critic, and later Lenin's." },
      { ref: "concept:vanguard-party", framing: "Lenin's answer to the question of organisation." },
      { ref: "debate:class-consciousness", framing: "How does a class become an actor?" },
      { ref: "debate:what-is-the-state", framing: "The question underneath all the others." },
      { ref: "concept:hegemony", framing: "Gramsci's rethinking after defeat in the West." },
    ],
  },
  {
    slug: "anarchism",
    title: "Exploring anarchism",
    entryLine: "Explore anarchism.",
    level: "introductory",
    estimatedTime: "About 2 hours",
    featured: true,
    sortOrder: 40,
    summary:
      "From 'property is theft' to social ecology: the anti-authoritarian current, its key figures and its arguments with Marxism.",
    steps: [
      { ref: "tendency:anarchism", framing: "An overview of the tradition and its shared commitments." },
      { ref: "thinker:proudhon", framing: "Mutualism and federation." },
      { ref: "thinker:bakunin", framing: "Collectivism and the critique of the workers' state." },
      { ref: "debate:what-is-the-state", framing: "Where anarchists and Marxists part ways." },
      { ref: "thinker:kropotkin", framing: "Anarchist communism, science and ethics." },
      { ref: "concept:mutual-aid", framing: "Cooperation as a factor of evolution." },
      { ref: "event:spanish-revolution", framing: "The largest anarchist revolution." },
      { ref: "thinker:bookchin", framing: "Anarchism meets ecology." },
    ],
  },
  {
    slug: "feminist-theory",
    title: "Following feminist theory",
    entryLine: "Follow feminist theory.",
    level: "intermediate",
    estimatedTime: "About 2 hours",
    featured: true,
    sortOrder: 50,
    summary:
      "How socialist feminists made the household, the body and reproductive labour central to the critique of capitalism.",
    steps: [
      { ref: "text:origin-of-the-family", framing: "Engels's early historical account — a starting point, and a target." },
      { ref: "concept:labour", framing: "What counts as labour — and what doesn't?" },
      { ref: "event:wages-for-housework", framing: "A campaign as a provocation." },
      { ref: "thinker:federici", framing: "Wages for Housework and the history of primitive accumulation." },
      { ref: "concept:social-reproduction", framing: "The theory that grew out of these debates." },
      { ref: "debate:revolutionary-subject", framing: "Who is the subject of anti-capitalist struggle?" },
    ],
  },
  {
    slug: "advanced-ideology-and-the-state",
    title: "Advanced: ideology, hegemony and the state",
    entryLine: "Go straight to advanced material.",
    level: "advanced",
    estimatedTime: "About 4 hours",
    featured: true,
    sortOrder: 60,
    summary:
      "A demanding route through twentieth-century theories of how capitalist societies reproduce themselves.",
    steps: [
      { ref: "concept:commodity-fetishism", framing: "Marx on how social relations appear as relations between things." },
      { ref: "concept:ideology", framing: "From 'ruling ideas' to material practices." },
      { ref: "concept:hegemony", framing: "Consent armoured by coercion." },
      { ref: "text:prison-notebooks", framing: "The notebooks themselves, in their fragmentary form." },
      { ref: "thinker:althusser", framing: "Structure, ideology and the subject." },
      { ref: "text:ideology-and-isas", framing: "The essay that defined a generation of theory." },
      { ref: "debate:what-is-the-state", framing: "Bringing the threads together." },
    ],
  },
];
