import type { SeedExcerpt, SeedRelationship } from "./types";

/*
 * Sample relationship graph: [from, TYPE, to, note?, weight?].
 * Inverse types (INFLUENCED_BY, CRITIQUED_BY, FOLLOWED_BY) are normalised by
 * the seeder — both spellings are shown here to demonstrate that.
 */
export const relationships: SeedRelationship[] = [
  /* — Thinker ↔ thinker ——————————————————————————————————————————— */
  ["thinker:hegel", "INFLUENCED", "thinker:marx", "Dialectic and philosophy of history, transformed into a materialist critique.", 3],
  ["thinker:hegel", "INFLUENCED", "thinker:bakunin", "Bakunin began as a Left Hegelian.", 2],
  ["thinker:hegel", "INFLUENCED", "thinker:fanon", "The lordship-and-bondage dialectic in Black Skin, White Masks.", 1],
  ["thinker:marx", "ASSOCIATED_WITH", "thinker:engels", "Lifelong collaborators from 1844.", 3],
  ["thinker:proudhon", "INFLUENCED", "thinker:marx", "Marx's early admiration for What Is Property?", 1],
  ["thinker:marx", "CRITIQUED", "thinker:proudhon", "The Poverty of Philosophy (1847).", 2],
  ["thinker:proudhon", "INFLUENCED", "thinker:bakunin", "Federalism and anti-statism.", 3],
  ["thinker:bakunin", "CRITIQUED", "thinker:marx", "Against the 'dictatorship of the proletariat' and centralisation in the International.", 3],
  ["thinker:marx", "CRITIQUED", "thinker:bakunin", "Conspectus of Statism and Anarchy (1874–75); the Hague Congress.", 2],
  ["thinker:bakunin", "INFLUENCED", "thinker:kropotkin", "From collectivism to anarchist communism.", 2],
  ["thinker:engels", "INFLUENCED", "thinker:bernstein", "Bernstein was Engels's close associate and literary executor.", 2],
  ["thinker:marx", "INFLUENCED", "thinker:lenin", undefined, 3],
  ["thinker:engels", "INFLUENCED", "thinker:lenin", "Especially Engels's writings on the state.", 2],
  ["thinker:marx", "INFLUENCED", "thinker:luxemburg", undefined, 3],
  ["thinker:luxemburg", "CRITIQUED", "thinker:bernstein", "Social Reform or Revolution? (1899).", 3],
  ["thinker:luxemburg", "CRITIQUED", "thinker:lenin", "On party organisation (1904) and Bolshevik policy (1918).", 3],
  ["thinker:luxemburg", "CRITIQUED_BY", "thinker:lenin", "On the national question (1914).", 1],
  ["thinker:marx", "INFLUENCED", "thinker:gramsci", undefined, 3],
  ["thinker:lenin", "INFLUENCED", "thinker:gramsci", "The question of hegemony in Russian Marxism.", 2],
  ["thinker:marx", "INFLUENCED", "thinker:althusser", undefined, 3],
  ["thinker:althusser", "RESPONDED_TO", "thinker:gramsci", "Valued Gramsci on the state, criticised his 'historicism'.", 1],
  ["thinker:marx", "INFLUENCED", "thinker:fanon", "Fanon 'stretched' Marxist categories for the colonial situation.", 2],
  ["thinker:kropotkin", "INFLUENCED", "thinker:bookchin", undefined, 2],
  ["thinker:bookchin", "CRITIQUED", "thinker:marx", "Listen, Marxist! (1969).", 2],
  ["thinker:federici", "INFLUENCED_BY", "thinker:marx", undefined, 2],
  ["thinker:federici", "CRITIQUED", "thinker:marx", "On primitive accumulation and unwaged reproductive labour.", 2],
  ["thinker:fanon", "INFLUENCED", "thinker:federici", "Federici draws on anti-colonial thought.", 1],

  /* — Thinker → tendency ————————————————————————————————————————— */
  ["thinker:hegel", "MEMBER_OF", "tendency:german-idealism"],
  ["thinker:marx", "MEMBER_OF", "tendency:marxism"],
  ["thinker:engels", "MEMBER_OF", "tendency:marxism"],
  ["thinker:proudhon", "MEMBER_OF", "tendency:mutualism"],
  ["thinker:proudhon", "MEMBER_OF", "tendency:anarchism"],
  ["thinker:bakunin", "MEMBER_OF", "tendency:anarchism"],
  ["thinker:kropotkin", "MEMBER_OF", "tendency:anarcho-communism"],
  ["thinker:kropotkin", "MEMBER_OF", "tendency:anarchism"],
  ["thinker:bernstein", "MEMBER_OF", "tendency:social-democracy"],
  ["thinker:lenin", "MEMBER_OF", "tendency:leninism"],
  ["thinker:lenin", "MEMBER_OF", "tendency:marxism"],
  ["thinker:luxemburg", "MEMBER_OF", "tendency:marxism"],
  ["thinker:gramsci", "MEMBER_OF", "tendency:western-marxism"],
  ["thinker:gramsci", "MEMBER_OF", "tendency:marxism"],
  ["thinker:althusser", "MEMBER_OF", "tendency:structural-marxism"],
  ["thinker:fanon", "MEMBER_OF", "tendency:anti-colonial-thought"],
  ["thinker:bookchin", "MEMBER_OF", "tendency:social-ecology"],
  ["thinker:federici", "MEMBER_OF", "tendency:marxist-feminism"],

  /* — Tendency ↔ tendency ———————————————————————————————————————— */
  ["tendency:german-idealism", "INFLUENCED", "tendency:marxism"],
  ["tendency:marxism", "INFLUENCED", "tendency:social-democracy"],
  ["tendency:marxism", "INFLUENCED", "tendency:leninism"],
  ["tendency:marxism", "INFLUENCED", "tendency:western-marxism"],
  ["tendency:marxism", "INFLUENCED", "tendency:structural-marxism"],
  ["tendency:marxism", "INFLUENCED", "tendency:marxist-feminism"],
  ["tendency:marxism", "INFLUENCED", "tendency:anti-colonial-thought"],
  ["tendency:anarchism", "CRITIQUED", "tendency:marxism", "The state, the party and authority."],
  ["tendency:mutualism", "INFLUENCED", "tendency:anarchism"],
  ["tendency:anarchism", "INFLUENCED", "tendency:anarcho-communism"],
  ["tendency:anarcho-communism", "INFLUENCED", "tendency:social-ecology"],
  ["tendency:leninism", "CRITIQUED", "tendency:social-democracy", "'Opportunism' and the Second International."],

  /* — Thinker → concept ———————————————————————————————————————————— */
  ["thinker:marx", "DEVELOPED", "concept:alienation", undefined, 3],
  ["thinker:marx", "DEVELOPED", "concept:commodity", undefined, 3],
  ["thinker:marx", "DEVELOPED", "concept:surplus-value", undefined, 3],
  ["thinker:marx", "DEVELOPED", "concept:historical-materialism", undefined, 3],
  ["thinker:marx", "DEVELOPED", "concept:class-struggle", undefined, 3],
  ["thinker:marx", "DEVELOPED", "concept:commodity-fetishism", undefined, 3],
  ["thinker:marx", "DEVELOPED", "concept:labour-power", undefined, 2],
  ["thinker:marx", "DEVELOPED", "concept:capitalism", "As a critique of the capitalist mode of production.", 3],
  ["thinker:marx", "DEVELOPED", "concept:exploitation", undefined, 2],
  ["thinker:marx", "DEVELOPED", "concept:ideology", undefined, 2],
  ["thinker:marx", "DEVELOPED", "concept:class", undefined, 2],
  ["thinker:engels", "DEVELOPED", "concept:historical-materialism", "Co-author of the materialist conception of history.", 3],
  ["thinker:engels", "DEVELOPED", "concept:dialectics", "The 'dialectics of nature'.", 2],
  ["thinker:hegel", "DEVELOPED", "concept:dialectics", undefined, 3],
  ["thinker:hegel", "ASSOCIATED_WITH", "concept:alienation", "Self-estrangement in the Phenomenology.", 2],
  ["thinker:proudhon", "DEVELOPED", "concept:private-property", "'Property is theft.'", 2],
  ["thinker:bakunin", "ASSOCIATED_WITH", "concept:the-state", undefined, 2],
  ["thinker:kropotkin", "DEVELOPED", "concept:mutual-aid", undefined, 3],
  ["thinker:lenin", "DEVELOPED", "concept:vanguard-party", undefined, 3],
  ["thinker:lenin", "DEVELOPED", "concept:imperialism", undefined, 3],
  ["thinker:luxemburg", "DEVELOPED", "concept:class-consciousness", "Through mass action.", 2],
  ["thinker:luxemburg", "DEVELOPED", "concept:imperialism", "Via the theory of accumulation.", 2],
  ["thinker:gramsci", "DEVELOPED", "concept:hegemony", undefined, 3],
  ["thinker:gramsci", "DEVELOPED", "concept:ideology", "Common sense and 'contradictory consciousness'.", 1],
  ["thinker:althusser", "DEVELOPED", "concept:ideology", "Ideological state apparatuses and interpellation.", 3],
  ["thinker:althusser", "CRITIQUED", "concept:alienation", "As a residue of Marx's pre-scientific humanism.", 2],
  ["thinker:fanon", "DEVELOPED", "concept:decolonisation", undefined, 3],
  ["thinker:bookchin", "DEVELOPED", "concept:social-ecology", undefined, 3],
  ["thinker:federici", "DEVELOPED", "concept:social-reproduction", undefined, 3],
  ["thinker:bernstein", "REJECTED", "concept:dialectics", "Regarded the Hegelian dialectic as a source of error in Marxist theory.", 1],

  /* — Concept ↔ concept ———————————————————————————————————————————— */
  ["concept:alienation", "RELATED_TO", "concept:commodity-fetishism", "A continuation in different vocabulary?", 3],
  ["concept:alienation", "RELATED_TO", "concept:labour", undefined, 2],
  ["concept:alienation", "RELATED_TO", "concept:labour-power", undefined, 2],
  ["concept:alienation", "RELATED_TO", "concept:commodity", undefined, 2],
  ["concept:alienation", "RELATED_TO", "concept:exploitation", undefined, 1],
  ["concept:alienation", "RELATED_TO", "concept:dialectics", "The Hegelian inheritance.", 1],
  ["concept:commodity", "RELATED_TO", "concept:value", undefined, 3],
  ["concept:commodity", "RELATED_TO", "concept:commodity-fetishism", undefined, 3],
  ["concept:commodity", "RELATED_TO", "concept:capitalism", undefined, 2],
  ["concept:value", "RELATED_TO", "concept:labour", undefined, 3],
  ["concept:value", "RELATED_TO", "concept:surplus-value", undefined, 3],
  ["concept:labour-power", "RELATED_TO", "concept:surplus-value", undefined, 3],
  ["concept:surplus-value", "RELATED_TO", "concept:exploitation", undefined, 3],
  ["concept:class", "RELATED_TO", "concept:class-struggle", undefined, 3],
  ["concept:class", "RELATED_TO", "concept:class-consciousness", undefined, 3],
  ["concept:class", "RELATED_TO", "concept:capitalism", undefined, 2],
  ["concept:historical-materialism", "RELATED_TO", "concept:class-struggle", undefined, 3],
  ["concept:historical-materialism", "RELATED_TO", "concept:dialectics", undefined, 2],
  ["concept:historical-materialism", "RELATED_TO", "concept:ideology", "Base and superstructure.", 2],
  ["concept:hegemony", "RELATED_TO", "concept:ideology", undefined, 3],
  ["concept:hegemony", "RELATED_TO", "concept:the-state", "The 'integral state'.", 3],
  ["concept:hegemony", "RELATED_TO", "concept:class-consciousness", undefined, 2],
  ["concept:the-state", "RELATED_TO", "concept:class-struggle", undefined, 2],
  ["concept:the-state", "RELATED_TO", "concept:vanguard-party", undefined, 2],
  ["concept:imperialism", "RELATED_TO", "concept:capitalism", undefined, 2],
  ["concept:imperialism", "RELATED_TO", "concept:decolonisation", undefined, 3],
  ["concept:social-reproduction", "RELATED_TO", "concept:labour", undefined, 3],
  ["concept:social-reproduction", "RELATED_TO", "concept:labour-power", "Who produces the worker?", 3],
  ["concept:mutual-aid", "RELATED_TO", "concept:social-ecology", undefined, 2],
  ["concept:private-property", "RELATED_TO", "concept:capitalism", undefined, 2],
  ["concept:capitalism", "RELATED_TO", "concept:exploitation", undefined, 2],

  /* — Authorship ———————————————————————————————————————————————————— */
  ["thinker:hegel", "WROTE", "text:phenomenology-of-spirit"],
  ["thinker:proudhon", "WROTE", "text:what-is-property"],
  ["thinker:marx", "WROTE", "text:economic-philosophic-manuscripts"],
  ["thinker:engels", "WROTE", "text:condition-working-class-england"],
  ["thinker:marx", "WROTE", "text:theses-on-feuerbach"],
  ["thinker:marx", "WROTE", "text:the-german-ideology"],
  ["thinker:engels", "WROTE", "text:the-german-ideology"],
  ["thinker:marx", "WROTE", "text:communist-manifesto"],
  ["thinker:engels", "WROTE", "text:communist-manifesto"],
  ["thinker:marx", "WROTE", "text:capital-volume-one"],
  ["thinker:bakunin", "WROTE", "text:statism-and-anarchy"],
  ["thinker:engels", "WROTE", "text:origin-of-the-family"],
  ["thinker:kropotkin", "WROTE", "text:the-conquest-of-bread"],
  ["thinker:kropotkin", "WROTE", "text:mutual-aid"],
  ["thinker:bernstein", "WROTE", "text:preconditions-of-socialism"],
  ["thinker:luxemburg", "WROTE", "text:social-reform-or-revolution"],
  ["thinker:luxemburg", "WROTE", "text:the-mass-strike"],
  ["thinker:luxemburg", "WROTE", "text:accumulation-of-capital"],
  ["thinker:luxemburg", "WROTE", "text:the-russian-revolution"],
  ["thinker:lenin", "WROTE", "text:what-is-to-be-done"],
  ["thinker:lenin", "WROTE", "text:imperialism-highest-stage"],
  ["thinker:lenin", "WROTE", "text:the-state-and-revolution"],
  ["thinker:gramsci", "WROTE", "text:prison-notebooks"],
  ["thinker:fanon", "WROTE", "text:black-skin-white-masks"],
  ["thinker:fanon", "WROTE", "text:the-wretched-of-the-earth"],
  ["thinker:althusser", "WROTE", "text:for-marx"],
  ["thinker:althusser", "WROTE", "text:ideology-and-isas"],
  ["thinker:federici", "WROTE", "text:wages-against-housework"],
  ["thinker:federici", "WROTE", "text:caliban-and-the-witch"],
  ["thinker:bookchin", "WROTE", "text:the-ecology-of-freedom"],

  /* — Text → concept / text ————————————————————————————————————————— */
  ["text:economic-philosophic-manuscripts", "DISCUSSES", "concept:alienation", "'Estranged Labour'.", 3],
  ["text:capital-volume-one", "DISCUSSES", "concept:commodity", "Chapter 1.", 3],
  ["text:capital-volume-one", "DISCUSSES", "concept:commodity-fetishism", "Chapter 1, section 4.", 3],
  ["text:capital-volume-one", "DISCUSSES", "concept:surplus-value", "Parts 3–5.", 3],
  ["text:capital-volume-one", "DISCUSSES", "concept:labour-power", "Chapter 6.", 3],
  ["text:capital-volume-one", "DISCUSSES", "concept:value", undefined, 3],
  ["text:capital-volume-one", "DISCUSSES", "concept:exploitation", undefined, 2],
  ["text:communist-manifesto", "DISCUSSES", "concept:class-struggle", undefined, 3],
  ["text:communist-manifesto", "DISCUSSES", "concept:class", undefined, 2],
  ["text:communist-manifesto", "DISCUSSES", "concept:private-property", "Abolition of bourgeois property.", 2],
  ["text:the-german-ideology", "DISCUSSES", "concept:historical-materialism", undefined, 3],
  ["text:the-german-ideology", "DISCUSSES", "concept:ideology", undefined, 3],
  ["text:the-german-ideology", "DISCUSSES", "concept:alienation", undefined, 1],
  ["text:theses-on-feuerbach", "DISCUSSES", "concept:historical-materialism", undefined, 2],
  ["text:what-is-property", "DISCUSSES", "concept:private-property", undefined, 3],
  ["text:statism-and-anarchy", "DISCUSSES", "concept:the-state", undefined, 3],
  ["text:the-state-and-revolution", "DISCUSSES", "concept:the-state", undefined, 3],
  ["text:what-is-to-be-done", "DISCUSSES", "concept:vanguard-party", undefined, 3],
  ["text:what-is-to-be-done", "DISCUSSES", "concept:class-consciousness", undefined, 3],
  ["text:imperialism-highest-stage", "DISCUSSES", "concept:imperialism", undefined, 3],
  ["text:accumulation-of-capital", "DISCUSSES", "concept:imperialism", undefined, 2],
  ["text:prison-notebooks", "DISCUSSES", "concept:hegemony", undefined, 3],
  ["text:prison-notebooks", "DISCUSSES", "concept:ideology", undefined, 2],
  ["text:mutual-aid", "DISCUSSES", "concept:mutual-aid", undefined, 3],
  ["text:the-wretched-of-the-earth", "DISCUSSES", "concept:decolonisation", undefined, 3],
  ["text:ideology-and-isas", "DISCUSSES", "concept:ideology", undefined, 3],
  ["text:ideology-and-isas", "DISCUSSES", "concept:the-state", undefined, 2],
  ["text:wages-against-housework", "DISCUSSES", "concept:social-reproduction", undefined, 3],
  ["text:caliban-and-the-witch", "DISCUSSES", "concept:social-reproduction", undefined, 2],
  ["text:the-ecology-of-freedom", "DISCUSSES", "concept:social-ecology", undefined, 3],
  ["text:origin-of-the-family", "DISCUSSES", "concept:private-property", undefined, 2],
  ["text:origin-of-the-family", "DISCUSSES", "concept:the-state", undefined, 2],
  ["text:social-reform-or-revolution", "RESPONDED_TO", "text:preconditions-of-socialism", undefined, 3],
  ["text:the-state-and-revolution", "RESPONDED_TO", "event:paris-commune", "Lenin's reading of Marx's The Civil War in France.", 3],
  ["text:for-marx", "RESPONDED_TO", "text:economic-philosophic-manuscripts", "The 'epistemological break'.", 2],

  /* — Events —————————————————————————————————————————————————————— */
  ["event:revolutions-of-1848", "ASSOCIATED_WITH", "text:communist-manifesto", "Published in London in February 1848, as revolution broke out in Paris."],
  ["event:revolutions-of-1848", "ASSOCIATED_WITH", "thinker:bakunin", "Took part in the Prague and Dresden risings."],
  ["event:first-international", "ASSOCIATED_WITH", "thinker:marx", "Drafted the Inaugural Address."],
  ["event:first-international", "ASSOCIATED_WITH", "thinker:bakunin"],
  ["event:paris-commune", "ASSOCIATED_WITH", "thinker:marx", "The Civil War in France (1871)."],
  ["event:paris-commune", "ASSOCIATED_WITH", "thinker:bakunin"],
  ["event:paris-commune", "INFLUENCED", "thinker:lenin", undefined, 2],
  ["event:hague-congress", "ASSOCIATED_WITH", "thinker:bakunin", "Expelled."],
  ["event:hague-congress", "ASSOCIATED_WITH", "thinker:marx"],
  ["event:first-international", "PRECEDES", "event:hague-congress"],
  ["event:revolution-1905", "INFLUENCED", "text:the-mass-strike", undefined, 3],
  ["event:revolution-1905", "PRECEDES", "event:october-revolution"],
  ["event:october-revolution", "ASSOCIATED_WITH", "thinker:lenin"],
  ["event:october-revolution", "FOLLOWED_BY", "event:revolution-1905"],
  ["event:spartacist-uprising", "ASSOCIATED_WITH", "thinker:luxemburg"],
  ["event:war-credits-1914", "ASSOCIATED_WITH", "thinker:luxemburg", "Led the internationalist opposition."],
  ["event:bolshevik-menshevik-split", "ASSOCIATED_WITH", "thinker:lenin"],
  ["event:biennio-rosso", "ASSOCIATED_WITH", "thinker:gramsci", "L'Ordine Nuovo and the factory councils."],
  ["event:gramsci-arrested", "ASSOCIATED_WITH", "thinker:gramsci"],
  ["event:algerian-war", "ASSOCIATED_WITH", "thinker:fanon"],
  ["event:wages-for-housework", "ASSOCIATED_WITH", "thinker:federici"],
  ["event:spanish-revolution", "ASSOCIATED_WITH", "tendency:anarchism"],
  ["event:french-revolution", "INFLUENCED", "thinker:hegel"],
  ["event:may-1968", "ASSOCIATED_WITH", "thinker:althusser", "Criticised by students — and by former student Rancière."],
  ["event:financial-crisis-2008", "PRECEDES", "event:occupy"],

  /* — Debates ———————————————————————————————————————————————————— */
  ["debate:what-is-the-state", "DISCUSSES", "concept:the-state", undefined, 3],
  ["debate:what-is-the-state", "DISCUSSES", "concept:hegemony", undefined, 2],
  ["debate:what-is-the-state", "DISCUSSES", "concept:vanguard-party", undefined, 1],
  ["debate:what-is-the-state", "DISCUSSES", "event:paris-commune", undefined, 2],
  ["debate:reform-or-revolution", "DISCUSSES", "concept:capitalism", undefined, 2],
  ["debate:class-consciousness", "DISCUSSES", "concept:class-consciousness", undefined, 3],
  ["debate:class-consciousness", "DISCUSSES", "concept:hegemony", undefined, 2],
  ["debate:can-capitalism-be-reformed", "DISCUSSES", "concept:capitalism", undefined, 3],
  ["debate:revolutionary-subject", "DISCUSSES", "concept:class", undefined, 3],
  ["debate:revolutionary-subject", "DISCUSSES", "concept:social-reproduction", undefined, 2],
  ["debate:revolutionary-subject", "DISCUSSES", "concept:decolonisation", undefined, 2],
  ["debate:what-is-the-state", "RELATED_TO", "debate:reform-or-revolution"],
  ["debate:reform-or-revolution", "RELATED_TO", "debate:can-capitalism-be-reformed"],
  ["debate:class-consciousness", "RELATED_TO", "debate:revolutionary-subject"],
  ["debate:what-is-the-state", "RELATED_TO", "debate:class-consciousness"],
];

/**
 * Excerpts. Only a handful of very widely reproduced passages are quoted;
 * they are flagged unverified until checked against the cited edition. Other
 * excerpts are references to passages, without quoted text.
 */
export const excerpts: SeedExcerpt[] = [
  {
    entity: "concept:alienation",
    text: "text:economic-philosophic-manuscripts",
    source: "src_1844_milligan",
    body: "The worker therefore only feels himself outside his work, and in his work feels outside himself.",
    locator: "First Manuscript, \"Estranged Labour\"",
  },
  {
    entity: "concept:alienation",
    text: "text:capital-volume-one",
    source: "src_capital_fowkes",
    body: "",
    locator: "Chapter 1, §4, \"The Fetishism of the Commodity and Its Secret\"",
    note: "Where the problematic of alienation reappears in the vocabulary of fetishism.",
  },
  {
    entity: "concept:alienation",
    text: "text:the-german-ideology",
    body: "",
    locator: "Part I, \"Feuerbach\"",
    note: "The division of labour and the 'estrangement' of social activity.",
  },
  {
    entity: "concept:commodity",
    text: "text:capital-volume-one",
    source: "src_capital_fowkes",
    body: "The wealth of societies in which the capitalist mode of production prevails appears as an 'immense collection of commodities'; the individual commodity appears as its elementary form.",
    locator: "Chapter 1, p. 125",
  },
  {
    entity: "concept:class-struggle",
    text: "text:communist-manifesto",
    source: "src_manifesto_moore",
    body: "The history of all hitherto existing society is the history of class struggles.",
    locator: "Section I, opening sentence",
  },
  {
    entity: "thinker:marx",
    text: "text:theses-on-feuerbach",
    source: "src_theses_feuerbach",
    body: "The philosophers have only interpreted the world, in various ways; the point is to change it.",
    locator: "Thesis XI",
  },
  {
    entity: "concept:hegemony",
    text: "text:prison-notebooks",
    source: "src_prison_notebooks",
    body: "The crisis consists precisely in the fact that the old is dying and the new cannot be born; in this interregnum a great variety of morbid symptoms appear.",
    locator: "p. 276",
  },
  {
    entity: "concept:surplus-value",
    text: "text:capital-volume-one",
    source: "src_capital_fowkes",
    body: "",
    locator: "Part Three, \"The Production of Absolute Surplus-Value\"",
  },
  {
    entity: "concept:the-state",
    text: "text:the-state-and-revolution",
    source: "src_state_revolution",
    body: "",
    locator: "Chapter I, \"Class Society and the State\"",
  },
];
