import type { SeedSource } from "./types";

/**
 * Sample bibliography. These are real publications, but the records are
 * seeded as examples of the citation system: confirm edition details before
 * relying on page references.
 */
const VERIFY = "Sample bibliographic record — confirm edition and pagination before citing.";

export const sources: SeedSource[] = [
  {
    id: "src_capital_fowkes",
    title: "Capital: A Critique of Political Economy, Volume One",
    author: "Karl Marx; trans. Ben Fowkes",
    publicationDate: "1976 [German original 1867]",
    publisher: "Penguin Books / New Left Review",
    sourceType: "PRIMARY",
    notes: VERIFY,
  },
  {
    id: "src_manifesto_moore",
    title: "Manifesto of the Communist Party",
    author: "Karl Marx and Friedrich Engels; trans. Samuel Moore",
    publicationDate: "1888 [German original 1848]",
    publisher: "William Reeves (London)",
    url: "https://www.marxists.org/archive/marx/works/1848/communist-manifesto/",
    sourceType: "PRIMARY",
    notes: VERIFY,
  },
  {
    id: "src_1844_milligan",
    title: "Economic and Philosophic Manuscripts of 1844",
    author: "Karl Marx; trans. Martin Milligan",
    publicationDate: "1959 [written 1844; first published 1932]",
    publisher: "Progress Publishers (Moscow)",
    url: "https://www.marxists.org/archive/marx/works/1844/manuscripts/preface.htm",
    sourceType: "PRIMARY",
    notes: VERIFY,
  },
  {
    id: "src_theses_feuerbach",
    title: "Theses on Feuerbach",
    author: "Karl Marx",
    publicationDate: "1888 [written 1845]",
    publisher: "Published by Engels as an appendix to Ludwig Feuerbach",
    url: "https://www.marxists.org/archive/marx/works/1845/theses/theses.htm",
    sourceType: "PRIMARY",
    notes: VERIFY,
  },
  {
    id: "src_prison_notebooks",
    title: "Selections from the Prison Notebooks",
    author: "Antonio Gramsci; ed. and trans. Quintin Hoare and Geoffrey Nowell Smith",
    publicationDate: "1971",
    publisher: "Lawrence & Wishart",
    sourceType: "PRIMARY",
    notes: VERIFY,
  },
  {
    id: "src_state_revolution",
    title: "The State and Revolution",
    author: "V. I. Lenin",
    publicationDate: "1918 [written 1917]",
    url: "https://www.marxists.org/archive/lenin/works/1917/staterev/",
    sourceType: "PRIMARY",
    notes: VERIFY,
  },
  {
    id: "src_reform_revolution",
    title: "Social Reform or Revolution?",
    author: "Rosa Luxemburg",
    publicationDate: "1899 [2nd edition 1908]",
    url: "https://www.marxists.org/archive/luxemburg/1900/reform-revolution/",
    sourceType: "PRIMARY",
    notes: VERIFY,
  },
  {
    id: "src_statism_anarchy",
    title: "Statism and Anarchy",
    author: "Mikhail Bakunin; ed. and trans. Marshall S. Shatz",
    publicationDate: "1990 [Russian original 1873]",
    publisher: "Cambridge University Press",
    sourceType: "PRIMARY",
    notes: VERIFY,
  },
  {
    id: "src_what_is_property",
    title: "What Is Property?",
    author: "Pierre-Joseph Proudhon; ed. Donald R. Kelley and Bonnie G. Smith",
    publicationDate: "1994 [French original 1840]",
    publisher: "Cambridge University Press",
    sourceType: "PRIMARY",
    notes: VERIFY,
  },
  {
    id: "src_mutual_aid",
    title: "Mutual Aid: A Factor of Evolution",
    author: "Peter Kropotkin",
    publicationDate: "1902",
    publisher: "William Heinemann (London)",
    sourceType: "PRIMARY",
    notes: VERIFY,
  },
  {
    id: "src_wretched",
    title: "The Wretched of the Earth",
    author: "Frantz Fanon; trans. Constance Farrington",
    publicationDate: "1963 [French original 1961]",
    publisher: "Grove Press",
    sourceType: "PRIMARY",
    notes: VERIFY,
  },
  {
    id: "src_caliban",
    title: "Caliban and the Witch: Women, the Body and Primitive Accumulation",
    author: "Silvia Federici",
    publicationDate: "2004",
    publisher: "Autonomedia",
    sourceType: "CONTEMPORARY",
    notes: VERIFY,
  },
  {
    id: "src_isa",
    title: "Ideology and Ideological State Apparatuses",
    author: "Louis Althusser; trans. Ben Brewster",
    publicationDate: "1971 [French original 1970]",
    publisher: "In Lenin and Philosophy and Other Essays, New Left Books",
    sourceType: "PRIMARY",
    notes: VERIFY,
  },
  {
    id: "src_preconditions",
    title: "The Preconditions of Socialism",
    author: "Eduard Bernstein; ed. and trans. Henry Tudor",
    publicationDate: "1993 [German original 1899]",
    publisher: "Cambridge University Press",
    sourceType: "PRIMARY",
    notes: VERIFY,
  },
  {
    id: "src_ecology_freedom",
    title: "The Ecology of Freedom",
    author: "Murray Bookchin",
    publicationDate: "1982",
    publisher: "Cheshire Books",
    sourceType: "PRIMARY",
    notes: VERIFY,
  },
  {
    id: "src_ollman_alienation",
    title: "Alienation: Marx's Conception of Man in Capitalist Society",
    author: "Bertell Ollman",
    publicationDate: "1971",
    publisher: "Cambridge University Press",
    sourceType: "ACADEMIC",
    notes: VERIFY,
  },
  {
    id: "src_kolakowski",
    title: "Main Currents of Marxism (3 vols.)",
    author: "Leszek Kołakowski",
    publicationDate: "1978",
    publisher: "Oxford University Press",
    sourceType: "ACADEMIC",
    notes: VERIFY,
  },
  {
    id: "src_anderson_western",
    title: "Considerations on Western Marxism",
    author: "Perry Anderson",
    publicationDate: "1976",
    publisher: "New Left Books",
    sourceType: "ACADEMIC",
    notes: VERIFY,
  },
  {
    id: "src_marshall_anarchism",
    title: "Demanding the Impossible: A History of Anarchism",
    author: "Peter Marshall",
    publicationDate: "1992",
    publisher: "HarperCollins",
    sourceType: "SECONDARY",
    notes: VERIFY,
  },
  {
    id: "src_hobsbawm_revolution",
    title: "The Age of Revolution: Europe 1789–1848",
    author: "Eric Hobsbawm",
    publicationDate: "1962",
    publisher: "Weidenfeld & Nicolson",
    sourceType: "HISTORICAL",
    notes: VERIFY,
  },
  {
    id: "src_bottomore_dictionary",
    title: "A Dictionary of Marxist Thought",
    author: "Tom Bottomore (ed.)",
    publicationDate: "1983",
    publisher: "Blackwell",
    sourceType: "REFERENCE",
    notes: VERIFY,
  },
  {
    id: "src_williams_keywords",
    title: "Keywords: A Vocabulary of Culture and Society",
    author: "Raymond Williams",
    publicationDate: "1976",
    publisher: "Fontana",
    sourceType: "REFERENCE",
    notes: VERIFY,
  },
  {
    id: "src_heinrich_capital",
    title: "An Introduction to the Three Volumes of Karl Marx's Capital",
    author: "Michael Heinrich",
    publicationDate: "2012",
    publisher: "Monthly Review Press",
    sourceType: "SECONDARY",
    notes: VERIFY,
  },
  {
    id: "src_srt_bhattacharya",
    title: "Social Reproduction Theory: Remapping Class, Recentering Oppression",
    author: "Tithi Bhattacharya (ed.)",
    publicationDate: "2017",
    publisher: "Pluto Press",
    sourceType: "CONTEMPORARY",
    notes: VERIFY,
  },
  {
    id: "src_mia",
    title: "Marxists Internet Archive",
    author: "Marxists Internet Archive volunteers",
    publicationDate: "1990s–",
    url: "https://www.marxists.org/",
    sourceType: "REFERENCE",
    notes: "Open-access library of primary texts in many languages.",
  },
];
