import type { SeedText } from "./types";

const MIA = "https://www.marxists.org";

export const texts: SeedText[] = [
  {
    slug: "phenomenology-of-spirit",
    title: "Phenomenology of Spirit",
    originalTitle: "Phänomenologie des Geistes",
    language: "German",
    form: "book",
    yearStart: 1807,
    difficulty: 3,
    sortOrder: 5,
    summary:
      "Hegel's account of consciousness developing through stages towards absolute knowing — including the famous dialectic of lordship and bondage.",
  },
  {
    slug: "what-is-property",
    title: "What Is Property?",
    originalTitle: "Qu'est-ce que la propriété ?",
    language: "French",
    form: "book",
    yearStart: 1840,
    difficulty: 2,
    sortOrder: 10,
    summary:
      "Proudhon's polemic against property as a right to income without labour, which made 'property is theft' a slogan of the age.",
    citations: [{ source: "src_what_is_property" }],
  },
  {
    slug: "economic-philosophic-manuscripts",
    title: "Economic and Philosophic Manuscripts of 1844",
    subtitle: "The Paris Manuscripts",
    originalTitle: "Ökonomisch-philosophische Manuskripte",
    language: "German",
    form: "manuscript",
    yearStart: 1844,
    publicationNote: "Written 1844; first published 1932",
    difficulty: 3,
    featured: true,
    sortOrder: 20,
    aliases: ["1844 Manuscripts", "Paris Manuscripts"],
    readingUrl: `${MIA}/archive/marx/works/1844/manuscripts/preface.htm`,
    summary:
      "Marx's unfinished notebooks on political economy and Hegel, containing his fullest early account of alienated labour.",
    citations: [{ source: "src_1844_milligan" }],
  },
  {
    slug: "condition-working-class-england",
    title: "The Condition of the Working Class in England",
    originalTitle: "Die Lage der arbeitenden Klasse in England",
    language: "German",
    form: "book",
    yearStart: 1845,
    difficulty: 1,
    sortOrder: 25,
    summary:
      "Engels's study of industrial Manchester, combining statistics, reportage and argument about the making of a working class.",
  },
  {
    slug: "theses-on-feuerbach",
    title: "Theses on Feuerbach",
    language: "German",
    form: "manuscript",
    yearStart: 1845,
    publicationNote: "Written 1845; published by Engels in 1888",
    difficulty: 2,
    sortOrder: 30,
    readingUrl: `${MIA}/archive/marx/works/1845/theses/theses.htm`,
    summary:
      "Eleven short notes in which Marx breaks with contemplative materialism and puts practice at the centre of philosophy.",
    citations: [{ source: "src_theses_feuerbach" }],
  },
  {
    slug: "the-german-ideology",
    title: "The German Ideology",
    originalTitle: "Die deutsche Ideologie",
    language: "German",
    form: "manuscript",
    yearStart: 1846,
    publicationNote: "Written 1845–46; first published in full 1932",
    difficulty: 2,
    sortOrder: 35,
    summary:
      "Marx and Engels's settling of accounts with the Young Hegelians, and the first statement of the materialist conception of history.",
  },
  {
    slug: "communist-manifesto",
    title: "Manifesto of the Communist Party",
    subtitle: "The Communist Manifesto",
    originalTitle: "Manifest der Kommunistischen Partei",
    language: "German",
    form: "pamphlet",
    yearStart: 1848,
    difficulty: 1,
    featured: true,
    sortOrder: 40,
    aliases: ["Communist Manifesto", "The Manifesto"],
    readingUrl: `${MIA}/archive/marx/works/1848/communist-manifesto/`,
    summary:
      "Written for the Communist League on the eve of the 1848 revolutions: a compressed history of class struggle and a programme for the proletariat.",
    citations: [{ source: "src_manifesto_moore" }],
  },
  {
    slug: "capital-volume-one",
    title: "Capital, Volume I",
    subtitle: "A Critique of Political Economy",
    originalTitle: "Das Kapital. Kritik der politischen Ökonomie",
    language: "German",
    form: "book",
    yearStart: 1867,
    difficulty: 3,
    featured: true,
    sortOrder: 50,
    aliases: ["Capital", "Das Kapital", "Kapital"],
    readingUrl: `${MIA}/archive/marx/works/1867-c1/`,
    summary:
      "Marx's analysis of the capitalist mode of production, from the commodity and money through surplus value to accumulation.",
    citations: [{ source: "src_capital_fowkes" }, { source: "src_heinrich_capital" }],
  },
  {
    slug: "statism-and-anarchy",
    title: "Statism and Anarchy",
    originalTitle: "Государственность и анархия",
    language: "Russian",
    form: "book",
    yearStart: 1873,
    difficulty: 2,
    sortOrder: 55,
    summary:
      "Bakunin's late critique of the German state and of Marxist politics, warning that a workers' state would produce a new ruling elite.",
    citations: [{ source: "src_statism_anarchy" }],
  },
  {
    slug: "origin-of-the-family",
    title: "The Origin of the Family, Private Property and the State",
    language: "German",
    form: "book",
    yearStart: 1884,
    difficulty: 2,
    sortOrder: 60,
    summary:
      "Engels's historical account linking the family, private property and the state — an early reference point for Marxist feminism.",
  },
  {
    slug: "the-conquest-of-bread",
    title: "The Conquest of Bread",
    originalTitle: "La Conquête du pain",
    language: "French",
    form: "book",
    yearStart: 1892,
    difficulty: 1,
    sortOrder: 65,
    summary:
      "Kropotkin's sketch of how a communist society could provide for everyone through free association and the abolition of wages.",
  },
  {
    slug: "preconditions-of-socialism",
    title: "The Preconditions of Socialism",
    subtitle: "Also translated as Evolutionary Socialism",
    originalTitle: "Die Voraussetzungen des Sozialismus und die Aufgaben der Sozialdemokratie",
    language: "German",
    form: "book",
    yearStart: 1899,
    difficulty: 2,
    sortOrder: 70,
    aliases: ["Evolutionary Socialism"],
    summary:
      "Bernstein's case for revising Marxist theory and embracing gradual, democratic reform.",
    citations: [{ source: "src_preconditions" }],
  },
  {
    slug: "social-reform-or-revolution",
    title: "Social Reform or Revolution?",
    originalTitle: "Sozialreform oder Revolution?",
    language: "German",
    form: "pamphlet",
    yearStart: 1899,
    publicationNote: "First as newspaper articles, 1898–99; second edition 1908",
    difficulty: 1,
    featured: true,
    sortOrder: 75,
    aliases: ["Reform or Revolution"],
    readingUrl: `${MIA}/archive/luxemburg/1900/reform-revolution/`,
    summary:
      "Luxemburg's reply to Bernstein: reforms matter, but cannot by themselves abolish capitalist relations of production.",
    citations: [{ source: "src_reform_revolution" }],
  },
  {
    slug: "what-is-to-be-done",
    title: "What Is to Be Done?",
    originalTitle: "Что делать?",
    language: "Russian",
    form: "pamphlet",
    yearStart: 1902,
    difficulty: 2,
    sortOrder: 80,
    summary:
      "Lenin's argument for a centralised party of professional revolutionaries to bring socialist consciousness to the workers' movement.",
  },
  {
    slug: "mutual-aid",
    title: "Mutual Aid: A Factor of Evolution",
    language: "English",
    form: "book",
    yearStart: 1902,
    difficulty: 1,
    sortOrder: 82,
    aliases: ["Mutual Aid"],
    summary:
      "Kropotkin's evidence, from biology to medieval cities, that cooperation is a central factor in evolution and social life.",
    citations: [{ source: "src_mutual_aid" }],
  },
  {
    slug: "the-mass-strike",
    title: "The Mass Strike, the Political Party and the Trade Unions",
    language: "German",
    form: "pamphlet",
    yearStart: 1906,
    difficulty: 1,
    sortOrder: 85,
    summary:
      "Luxemburg's analysis of the 1905 Russian Revolution, emphasising the spontaneous creativity of mass action.",
  },
  {
    slug: "accumulation-of-capital",
    title: "The Accumulation of Capital",
    originalTitle: "Die Akkumulation des Kapitals",
    language: "German",
    form: "book",
    yearStart: 1913,
    difficulty: 3,
    sortOrder: 88,
    summary:
      "Luxemburg's argument that capitalist accumulation depends on expansion into non-capitalist territories — a theory of imperialism.",
  },
  {
    slug: "imperialism-highest-stage",
    title: "Imperialism, the Highest Stage of Capitalism",
    language: "Russian",
    form: "pamphlet",
    yearStart: 1917,
    publicationNote: "Written 1916; published 1917",
    difficulty: 2,
    sortOrder: 90,
    summary:
      "Lenin's 'popular outline' linking monopoly, finance capital and the division of the world among the great powers.",
  },
  {
    slug: "the-state-and-revolution",
    title: "The State and Revolution",
    originalTitle: "Государство и революция",
    language: "Russian",
    form: "book",
    yearStart: 1917,
    publicationNote: "Written August–September 1917; published 1918",
    difficulty: 2,
    featured: true,
    sortOrder: 95,
    readingUrl: `${MIA}/archive/lenin/works/1917/staterev/`,
    summary:
      "Lenin's reconstruction of Marx and Engels on the state: the bourgeois state must be smashed, replaced by a Commune-type workers' state that will wither away.",
    citations: [{ source: "src_state_revolution" }],
  },
  {
    slug: "the-russian-revolution",
    title: "The Russian Revolution",
    language: "German",
    form: "pamphlet",
    yearStart: 1918,
    publicationNote: "Written 1918; published 1922",
    difficulty: 1,
    sortOrder: 98,
    summary:
      "Luxemburg's solidaristic but sharp critique of Bolshevik policy, defending democracy and freedom of dissent within the revolution.",
  },
  {
    slug: "prison-notebooks",
    title: "Prison Notebooks",
    originalTitle: "Quaderni del carcere",
    language: "Italian",
    form: "notebooks",
    yearStart: 1929,
    yearEnd: 1935,
    publicationNote: "Written 1929–35; published in Italian from 1948",
    difficulty: 3,
    featured: true,
    sortOrder: 100,
    aliases: ["Quaderni del carcere", "Selections from the Prison Notebooks"],
    summary:
      "Gramsci's fragmentary notes on hegemony, intellectuals, the state, common sense and Italian history.",
    citations: [{ source: "src_prison_notebooks" }],
  },
  {
    slug: "black-skin-white-masks",
    title: "Black Skin, White Masks",
    originalTitle: "Peau noire, masques blancs",
    language: "French",
    form: "book",
    yearStart: 1952,
    difficulty: 2,
    sortOrder: 105,
    summary:
      "Fanon's analysis of the psychological experience of racism and colonial domination.",
  },
  {
    slug: "the-wretched-of-the-earth",
    title: "The Wretched of the Earth",
    originalTitle: "Les Damnés de la Terre",
    language: "French",
    form: "book",
    yearStart: 1961,
    difficulty: 2,
    featured: true,
    sortOrder: 110,
    summary:
      "Fanon's theory of decolonisation, written during the Algerian war: on violence, national consciousness and the colonised peasantry.",
    citations: [{ source: "src_wretched" }],
  },
  {
    slug: "for-marx",
    title: "For Marx",
    originalTitle: "Pour Marx",
    language: "French",
    form: "book",
    yearStart: 1965,
    difficulty: 3,
    sortOrder: 115,
    summary:
      "Althusser's essays arguing for an 'epistemological break' between the young and the mature Marx.",
  },
  {
    slug: "ideology-and-isas",
    title: "Ideology and Ideological State Apparatuses",
    language: "French",
    form: "essay",
    yearStart: 1970,
    difficulty: 3,
    sortOrder: 120,
    aliases: ["ISAs essay"],
    summary:
      "Althusser's essay on how schools, families, churches and media reproduce the relations of production by constituting subjects.",
    citations: [{ source: "src_isa" }],
  },
  {
    slug: "wages-against-housework",
    title: "Wages Against Housework",
    language: "English",
    form: "pamphlet",
    yearStart: 1975,
    difficulty: 1,
    sortOrder: 125,
    summary:
      "Federici's pamphlet arguing that demanding wages for housework exposes the unwaged labour on which capitalism depends.",
  },
  {
    slug: "the-ecology-of-freedom",
    title: "The Ecology of Freedom",
    subtitle: "The Emergence and Dissolution of Hierarchy",
    language: "English",
    form: "book",
    yearStart: 1982,
    difficulty: 2,
    sortOrder: 130,
    summary:
      "Bookchin's history of hierarchy and his case for an ecological society grounded in freedom.",
    citations: [{ source: "src_ecology_freedom" }],
  },
  {
    slug: "caliban-and-the-witch",
    title: "Caliban and the Witch",
    subtitle: "Women, the Body and Primitive Accumulation",
    language: "English",
    form: "book",
    yearStart: 2004,
    difficulty: 2,
    featured: true,
    sortOrder: 135,
    summary:
      "Federici's feminist history of the transition to capitalism, centred on enclosure, the witch-hunts and the disciplining of reproductive labour.",
    citations: [{ source: "src_caliban" }],
  },
];
